### ISSUE TITLE
Adjust the pipeline to other model organisms

### ISSUE THREAD

**Issue by Midnighter** [saezlab/ocean#8]
Hi,

I would like to try this tool with a genome-scale model of [_Pseudomonas putida_ KT2440](http://bigg.ucsd.edu/models/iJN1463). Can you describe what is necessary to do so, please?

**Comment by adugourd** [comment]
We will update the package soon to streamline such process as it will require tinckering a bit with the code as the moment to get it done. 

For now, I contacted you by email to chat about it in more details.

Cheers,

Aurelien
